added remove and pop on list type
Parth/db-rs pull request #12
Opened 2023-03-26 22:28 UTC by ad-tra

2023-03-26 23:10 UTC, Parth commented on db/src/list.rs
> +    Pop(),
prob not needed

2023-03-27 17:44 UTC, ad-tra commented
- [ ] publish `db-rs`
- [ ] publish `db-rs-derive`

2023-03-27 17:56 UTC, Parth requested changes
tests?

2023-03-27 18:03 UTC, Parth approved these changes

2023-03-27 18:04 UTC, merged